<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="battlepass_seasons">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="season" type="DaevaPassSeason" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="DaevaPassSeason">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="active" type="xs:int"/>
        <xs:attribute name="max_lv" type="xs:int"/>
        <xs:attribute name="unlock_lv" type="xs:int"/>
        <xs:attribute name="unlock_quna" type="xs:int"/>
        <xs:attribute name="exp_quna" type="xs:int"/>
        <xs:attribute name="pass_start" type="xs:string"/>
        <xs:attribute name="mission_end" type="xs:string"/>
        <xs:attribute name="reward_time" type="xs:string"/>
        <xs:attribute name="pass_end" type="xs:string"/>
    </xs:complexType>
</xs:schema>
